---
title: "Data Summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
load(here::here("data - output", "jeopardy.RData"))
```

```{r echo=FALSE}
df_airdate %>% 
  head() %>% 
  kbl(caption = "df_airdate") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_board %>% 
  head() %>% 
  kbl(caption = "df_board") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_contestants %>% 
  head() %>% 
  kbl(caption = "df_contestants") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_doubles %>% 
  head() %>% 
  kbl(caption = "df_doubles") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_player_ids %>% 
  head() %>% 
  kbl(caption = "df_player_ids") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_scores %>% 
  head() %>% 
  kbl(caption = "df_scores") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

df_synopsis %>% 
  head() %>% 
  kbl(caption = "df_synopsis") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```